---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  # namespace: test
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      volumes:
      - name: {{ .Values.name }}-volume
        persistentVolumeClaim:
          claimName: {{ .Values.name }}-pvc-{{ Release.Namespace }}
      containers:
      - name: nginx-vol
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/usr/share/nginx/html/test"
          name: {{ .Values.name }}-volume