kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-ingress-traffic-only-from-same-namespace
  namespace: {{ .Release.Namespace}}
spec:
  podSelector:
    matchLabels: {}
  ingress:
  - from:
    - podSelector:
        matchLabels: {}
      namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ .Release.Namespace}}