apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  ports:
  - name: tcp80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: {{ .Values.name }}
  type: ClusterIP